export const finalStates = [
    "IDENTIFIER", 
    "INCREMENT",
    "DECREMENT",
    "INTEGER",
    "DECIMAL",
    "MULTILINE_COMMENT", // /* */
    "LINE_COMMENT", // //
    "ASSIGNMENT", // =
    "ARITHMETIC_OPERATOR_PLUS", // +
    "ARITHMETIC_OPERATOR_MUL", // *  
     "ARITHMETIC_OPERATOR_MOD", // % 
    "ARITHMETIC_OPERATOR_MINUS", // -
    "ARITHMETIC_OPERATOR_DIV", //  /
    "RELATIONAL_OPERATOR",  // <>
    "RELATIONAL_OPERATOR_EQUAL", // ==
    "LOGICAL_OPERATOR_NOT",  // !=
    "LOGICAL_OPERATOR_AND_AND", // &&
    "LOGICAL_OPERATOR_OR_OR", // ||
    "BRACE", 
    "PARENTHESIS",
    "STRING",
  ]